server:
  port: 7070
logging:
  level:
    de.enrhop.examples.springcloud.service1: DEBUG
    reactor.netty: DEBUG
    reactor.netty.http.client logging: DEBUG
    reactor.netty.http.client.HttpClient: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: TRACE
    org.springframework.security: DEBUG
    org.springframework.web.reactive.function.client: TRACE
spring:
  application:
    name: api-service-1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/master
          jwk-set-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/certs
        opaquetoken:
          introspection-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/token/introspect
          client-id: springcloud-api-gateway
          client-secret: dcf593f2-d2d0-448a-81b0-af47b0a4e6bd
